apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunbb-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bunbb-api
  template:
    metadata:
      labels:
        app: bunbb-api
    spec:
      containers:
      - name: bunbb-api
        image: docker.site/bunbb:0.1.3
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: docker-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: bunbb-api-service
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  type: LoadBalancer
  externalIPs:
    - 10.152.183.154
  selector:
    app: bunbb-api
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bunbb-api-ingress
spec:
  rules:
  - host: kuber.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bunbb-api-service
            port:
              number: 3030

